@baseUrl = http://localhost:8000

POST {{baseUrl}}/api/wilders HTTP/1.1
content-type: application/json

{
    "name":"Bob",
    "city": "Paris",
    "skills":[
        {"title":"express", "votes":5},
        {"title":"mongo", "votes":12}
    ]
}

### GET
GET {{baseUrl}}/api/wilders HTTP/1.1

### Error 404
GET {{baseUrl}}/api/wilders/blabla HTTP/1.1

###
@_id=5fa2d8ca1b68a3a5c7534d3f
PUT {{baseUrl}}/api/wilder/{{_id}} HTTP/1.1
content-type: application/json

{
    "name":"Bobby",
    "city": "Berlin",
    "skills":[
        {"title":"express", "votes":5},
        {"title":"mongo", "votes":12}
    ]
}

###
@_id=5fa3cfd295ab5016894410b5
DELETE http://localhost:8000/api/wilder/{{_id}} HTTP/1.1
content-type: application/json

{
    "_id": "5fa274fb853003144f615957"
}