@baseUrl = http://localhost:8000

POST {{baseUrl}}/api/wilders HTTP/1.1
content-type: application/json

{
    "name":"Http Wildreefzfeerss 1d1",
    "city": "Paris",
    "skills":[
        {"title":"express", "votes":5},
        {"title":"mongo", "votes":12}
    ]
}

### GET
GET {{baseUrl}}/api/wilders HTTP/1.1

### Error 404
GET {{baseUrl}}/api/wilders/blabla HTTP/1.1

###
@id=5fa291865e9f0935ad23c1c6
PUT {{baseUrl}}/api/wilder/{{id}} HTTP/1.1
content-type: application/json

{
    "name":"Bobby",
    "city": "Berlin",
    "skills":[
        {"title":"express", "votes":5},
        {"title":"mongo", "votes":12}
    ]
}

###
@id=5fa2d9cf5c38b8a8354e7c9f
DELETE http://localhost:8000/api/wilder/{{id}} HTTP/1.1
content-type: application/json

{
    "_id": "5fa274fb853003144f615957"
}